config/routes.rb
Glee::Application.routes.draw do
  resources :storythemes

  resources :themes

  resources :storyrelations

  resources :relationships

  resources :ships

  resources :protagnists

  resources :characters

  resources :stories

  resources :authors

  get "home/index"

  root :to => 'stories#index'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :ship
  belongs_to :character
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # GET /relationships
  # GET /relationships.json
  def index
    @relationships = Relationship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @relationships }
    end
  end

  # GET /relationships/1
  # GET /relationships/1.json
  def show
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @relationship }
    end
  end

  # GET /relationships/new
  # GET /relationships/new.json
  def new
    @relationship = Relationship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @relationship }
    end
  end

  # GET /relationships/1/edit
  def edit
    @relationship = Relationship.find(params[:id])
  end

  # POST /relationships
  # POST /relationships.json
  def create
    @relationship = Relationship.new(params[:relationship])

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to @relationship, notice: 'Relationship was successfully created.' }
        format.json { render json: @relationship, status: :created, location: @relationship }
      else
        format.html { render action: "new" }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /relationships/1
  # PUT /relationships/1.json
  def update
    @relationship = Relationship.find(params[:id])

    respond_to do |format|
      if @relationship.update_attributes(params[:relationship])
        format.html { redirect_to @relationship, notice: 'Relationship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1
  # DELETE /relationships/1.json
  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy

    respond_to do |format|
      format.html { redirect_to relationships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.haml
= form_for @relationship do |f|
  -if @relationship.errors.any?
    #error_explanation
      %h2= "#{pluralize(@relationship.errors.count, "error")} prohibited this relationship from being saved:"
      %ul
        - @relationship.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/relationships/edit.html.haml
%h1 Editing relationship

= render 'form'

= link_to 'Show', @relationship
\|
= link_to 'Back', relationships_path

app/views/relationships/index.html.haml
%h1 Listing relationships

%table
  %tr
    %th
    %th
    %th

  - @relationships.each do |relationship|
    %tr
      %td= link_to 'Show', relationship
      %td= link_to 'Edit', edit_relationship_path(relationship)
      %td= link_to 'Destroy', relationship, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Relationship', new_relationship_path

app/views/relationships/new.html.haml
%h1 New relationship

= render 'form'

= link_to 'Back', relationships_path

app/views/relationships/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_relationship_path(@relationship)
\|
= link_to 'Back', relationships_path