config/routes.rb
Glee::Application.routes.draw do
  resources :storythemes

  resources :themes

  resources :storyrelations

  resources :relationships

  resources :ships

  resources :protagnists

  resources :characters

  resources :stories

  resources :authors

  get "home/index"

  root :to => 'stories#index'

end

app/models/protagnist.rb
class Protagnist < ActiveRecord::Base
  # This is for the many-to-many relation ship between character and stories the name is kind of terrible

  belongs_to :story
  belongs_to :character
end

app/controllers/protagnists_controller.rb
class ProtagnistsController < ApplicationController
  # GET /protagnists
  # GET /protagnists.json
  def index
    @protagnists = Protagnist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @protagnists }
    end
  end

  # GET /protagnists/1
  # GET /protagnists/1.json
  def show
    @protagnist = Protagnist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @protagnist }
    end
  end

  # GET /protagnists/new
  # GET /protagnists/new.json
  def new
    @protagnist = Protagnist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @protagnist }
    end
  end

  # GET /protagnists/1/edit
  def edit
    @protagnist = Protagnist.find(params[:id])
  end

  # POST /protagnists
  # POST /protagnists.json
  def create
    @protagnist = Protagnist.new(params[:protagnist])

    respond_to do |format|
      if @protagnist.save
        format.html { redirect_to @protagnist, notice: 'Protagnist was successfully created.' }
        format.json { render json: @protagnist, status: :created, location: @protagnist }
      else
        format.html { render action: "new" }
        format.json { render json: @protagnist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /protagnists/1
  # PUT /protagnists/1.json
  def update
    @protagnist = Protagnist.find(params[:id])

    respond_to do |format|
      if @protagnist.update_attributes(params[:protagnist])
        format.html { redirect_to @protagnist, notice: 'Protagnist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @protagnist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /protagnists/1
  # DELETE /protagnists/1.json
  def destroy
    @protagnist = Protagnist.find(params[:id])
    @protagnist.destroy

    respond_to do |format|
      format.html { redirect_to protagnists_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/protagnists_helper.rb
module ProtagnistsHelper
end

app/views/protagnists/_form.html.haml
= form_for @protagnist do |f|
  -if @protagnist.errors.any?
    #error_explanation
      %h2= "#{pluralize(@protagnist.errors.count, "error")} prohibited this protagnist from being saved:"
      %ul
        - @protagnist.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :story_id
    = f.number_field :story_id
  .field
    = f.label :character_id
    = f.number_field :character_id
  .actions
    = f.submit 'Save'

app/views/protagnists/edit.html.haml
%h1 Editing protagnist

= render 'form'

= link_to 'Show', @protagnist
\|
= link_to 'Back', protagnists_path

app/views/protagnists/index.html.haml
%h1 Listing protagnists

%table
  %tr
    %th Story
    %th Character
    %th
    %th
    %th

  - @protagnists.each do |protagnist|
    %tr
      %td= protagnist.story_id
      %td= protagnist.character_id
      %td= link_to 'Show', protagnist
      %td= link_to 'Edit', edit_protagnist_path(protagnist)
      %td= link_to 'Destroy', protagnist, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Protagnist', new_protagnist_path

app/views/protagnists/new.html.haml
%h1 New protagnist

= render 'form'

= link_to 'Back', protagnists_path

app/views/protagnists/show.html.haml
%p#notice= notice

%p
  %b Story:
  = @protagnist.story_id
%p
  %b Character:
  = @protagnist.character_id

= link_to 'Edit', edit_protagnist_path(@protagnist)
\|
= link_to 'Back', protagnists_path