config/routes.rb
Glee::Application.routes.draw do
  resources :storythemes

  resources :themes

  resources :storyrelations

  resources :relationships

  resources :ships

  resources :protagnists

  resources :characters

  resources :stories

  resources :authors

  get "home/index"

  root :to => 'stories#index'

end

app/models/storyrelation.rb
class Storyrelation < ActiveRecord::Base
  belongs_to :story
  belongs_to :ship
end

app/controllers/storyrelations_controller.rb
class StoryrelationsController < ApplicationController
  # GET /storyrelations
  # GET /storyrelations.json
  def index
    @storyrelations = Storyrelation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @storyrelations }
    end
  end

  # GET /storyrelations/1
  # GET /storyrelations/1.json
  def show
    @storyrelation = Storyrelation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @storyrelation }
    end
  end

  # GET /storyrelations/new
  # GET /storyrelations/new.json
  def new
    @storyrelation = Storyrelation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @storyrelation }
    end
  end

  # GET /storyrelations/1/edit
  def edit
    @storyrelation = Storyrelation.find(params[:id])
  end

  # POST /storyrelations
  # POST /storyrelations.json
  def create
    @storyrelation = Storyrelation.new(params[:storyrelation])

    respond_to do |format|
      if @storyrelation.save
        format.html { redirect_to @storyrelation, notice: 'Storyrelation was successfully created.' }
        format.json { render json: @storyrelation, status: :created, location: @storyrelation }
      else
        format.html { render action: "new" }
        format.json { render json: @storyrelation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /storyrelations/1
  # PUT /storyrelations/1.json
  def update
    @storyrelation = Storyrelation.find(params[:id])

    respond_to do |format|
      if @storyrelation.update_attributes(params[:storyrelation])
        format.html { redirect_to @storyrelation, notice: 'Storyrelation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @storyrelation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storyrelations/1
  # DELETE /storyrelations/1.json
  def destroy
    @storyrelation = Storyrelation.find(params[:id])
    @storyrelation.destroy

    respond_to do |format|
      format.html { redirect_to storyrelations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/storyrelations_helper.rb
module StoryrelationsHelper
end

app/views/storyrelations/_form.html.haml
= form_for @storyrelation do |f|
  -if @storyrelation.errors.any?
    #error_explanation
      %h2= "#{pluralize(@storyrelation.errors.count, "error")} prohibited this storyrelation from being saved:"
      %ul
        - @storyrelation.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :story_id
    = f.number_field :story_id
  .field
    = f.label :ship_id
    = f.number_field :ship_id
  .actions
    = f.submit 'Save'

app/views/storyrelations/edit.html.haml
%h1 Editing storyrelation

= render 'form'

= link_to 'Show', @storyrelation
\|
= link_to 'Back', storyrelations_path

app/views/storyrelations/index.html.haml
%h1 Listing storyrelations

%table
  %tr
    %th Story
    %th Ship
    %th
    %th
    %th

  - @storyrelations.each do |storyrelation|
    %tr
      %td= storyrelation.story_id
      %td= storyrelation.ship_id
      %td= link_to 'Show', storyrelation
      %td= link_to 'Edit', edit_storyrelation_path(storyrelation)
      %td= link_to 'Destroy', storyrelation, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Storyrelation', new_storyrelation_path

app/views/storyrelations/new.html.haml
%h1 New storyrelation

= render 'form'

= link_to 'Back', storyrelations_path

app/views/storyrelations/show.html.haml
%p#notice= notice

%p
  %b Story:
  = @storyrelation.story_id
%p
  %b Ship:
  = @storyrelation.ship_id

= link_to 'Edit', edit_storyrelation_path(@storyrelation)
\|
= link_to 'Back', storyrelations_path