config/routes.rb
Glee::Application.routes.draw do
  resources :storythemes

  resources :themes

  resources :storyrelations

  resources :relationships

  resources :ships

  resources :protagnists

  resources :characters

  resources :stories

  resources :authors

  get "home/index"

  root :to => 'stories#index'

end

app/models/ship.rb
class Ship < ActiveRecord::Base
  has_many :relationships
  has_many :characters, :through => :relationships

  has_many :storyrelations
  has_many :stories, :through => :storyrelations
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  # GET /ships
  # GET /ships.json
  def index
    @ships = Ship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ships }
    end
  end

  # GET /ships/1
  # GET /ships/1.json
  def show
    @ship = Ship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ship }
    end
  end

  # GET /ships/new
  # GET /ships/new.json
  def new
    update_ships
    @ship = Ship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ship }
    end
  end

  # GET /ships/1/edit
  def edit
    @ship = Ship.find(params[:id])
  end

  # POST /ships
  # POST /ships.json
  def create
    @ship = Ship.new(params[:ship])

    respond_to do |format|
      if @ship.save
        format.html { redirect_to @ship, notice: 'Ship was successfully created.' }
        format.json { render json: @ship, status: :created, location: @ship }
      else
        format.html { render action: "new" }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ships/1
  # PUT /ships/1.json
  def update
    @ship = Ship.find(params[:id])

    respond_to do |format|
      if @ship.update_attributes(params[:ship])
        format.html { redirect_to @ship, notice: 'Ship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ships/1
  # DELETE /ships/1.json
  def destroy
    @ship = Ship.find(params[:id])
    @ship.destroy

    respond_to do |format|
      format.html { redirect_to ships_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/ships/_form.html.haml
= form_for @ship do |f|
  -if @ship.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ship.errors.count, "error")} prohibited this ship from being saved:"
      %ul
        - @ship.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/ships/edit.html.haml
%h1 Editing ship

= render 'form'

= link_to 'Show', @ship
\|
= link_to 'Back', ships_path

app/views/ships/index.html.haml
%h1 Listing ships

%table
  %tr
    %th Name
    %th Characters


  - @ships.each do |ship|
    %tr
      %td= ship.name
      %td
        - ship.characters.each do |character|
          =character.ff_name

      -#%td= link_to 'Show', ship
      -#%td= link_to 'Edit', edit_ship_path(ship)
      -#%td= link_to 'Destroy', ship, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Ship', new_ship_path

app/views/ships/new.html.haml
%h1 New ships Created

=# render 'form'

= link_to 'Back', ships_path

app/views/ships/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @ship.name

= link_to 'Edit', edit_ship_path(@ship)
\|
= link_to 'Back', ships_path